// ─── MCP runtime status vocabulary — HAND-SYNCED COPY ──────────────────────
//
// DO NOT EDIT THIS FILE DIRECTLY. It is a manual copy of the source of truth:
//     microservice/amadeus-core/src/types/mcpStatus.ts
// If you need to change the status vocabulary, change it THERE first, then
// mirror the MCP_STATUSES array here. A drift guard in the amadeus-core test
// suite (test/mcpStatusContract.test.ts) fails loudly if the two diverge.
//
// Why a copy and not a shared import: the FE and BE are fully independent
// packages (no workspace tooling; Next's Turbopack root is pinned to this
// dir), so a cross-package import would mean coupling the two builds for six
// strings. See the source-of-truth file for the full rationale and the
// trigger condition for revisiting this.

export const MCP_STATUSES = [
  'running', // process alive AND port verified listening (sse only)
  'starting', // spawned, port not yet proven listening
  'stopped', // intentionally stopped (manual restart, idle-stop, or obsolete)
  'crashed', // exited without being asked to; last_error is set
  'on-demand', // stdio tool — no persistent process, spawned per call
  'unknown', // no data yet, or a reading older than the staleness threshold
] as const;

export type McpStatus = (typeof MCP_STATUSES)[number];

export const MCP_METHODS = ['stdio', 'sse'] as const;
export type McpMethod = (typeof MCP_METHODS)[number];

/**
 * Narrow any raw string (a wire value from the API) to a known McpStatus,
 * falling back to 'unknown' for anything unrecognised. The UI MUST route
 * every status through here and never assume the union is exhaustive — that
 * is what keeps a BE/FE drift a cosmetic one-release bug rather than a
 * crashed render or a dead tool mislabelled as running.
 */
export function toMcpStatus(value: string | null | undefined): McpStatus {
  return (MCP_STATUSES as readonly string[]).includes(value as string)
    ? (value as McpStatus)
    : 'unknown';
}
